webappfile:
  uploadPath: /opt/jar/images/qn
spring:
  datasource:
    username: ym_new
    password: ym_new
    url: jdbc:mysql://139.159.136.88:3306/ym_new?useUnicode=true&useAffectedRows=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/,classpath:/views/,file:${webappfile.uploadPath}
    chain:
      cache: true
  thymeleaf:
    cache: true

server:
  port: 8080