spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ym_new?useUnicode=true&useAffectedRows=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: resources/**,static/**,templates/**   #设置重启的目录
      exclude: data/**  #该目录下的内容修改不重启
  resources:
    static-locations: classpath:/static/,classpath:/views/
#  messages:
#    basename: messages
#    encoding: UTF-8


# mybatis 控制台打印sql
logging:
  level:
    com.fovsoft.gn.mapper: debug

server:
  port: 8080